spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/dbUsers
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
