server:
  port: 9090

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/dbUsers
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9093/eureka/
